//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_gbdk_rocks_H
#define METASPRITE_gbdk_rocks_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define gbdk_rocks_TILE_ORIGIN 0
#define gbdk_rocks_TILE_W 8
#define gbdk_rocks_TILE_H 8
#define gbdk_rocks_WIDTH 160
#define gbdk_rocks_HEIGHT 144
#define gbdk_rocks_TILE_COUNT 139
#define gbdk_rocks_PALETTE_COUNT 1
#define gbdk_rocks_COLORS_PER_PALETTE 4
#define gbdk_rocks_TOTAL_COLORS 4
#define gbdk_rocks_MAP_ATTRIBUTES 0

BANKREF_EXTERN(gbdk_rocks)

extern const palette_color_t gbdk_rocks_palettes[4];
extern const uint8_t gbdk_rocks_tiles[2224];

extern const unsigned char gbdk_rocks_map[360];

#endif
