//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_roleyMap1_H
#define METASPRITE_roleyMap1_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define roleyMap1_TILE_ORIGIN 0
#define roleyMap1_TILE_W 8
#define roleyMap1_TILE_H 8
#define roleyMap1_WIDTH 32
#define roleyMap1_HEIGHT 18
#define roleyMap1_TILE_COUNT 32
#define roleyMap1_PALETTE_COUNT 1
#define roleyMap1_COLORS_PER_PALETTE 4
#define roleyMap1_TOTAL_COLORS 4
#define roleyMap1_MAP_ATTRIBUTES 0

BANKREF_EXTERN(roleyMap1)

extern const palette_color_t roleyMap1_palettes[4];
extern const uint8_t roleyMap1_tiles[5000];

extern const unsigned char roleyMap1_map[5000];

#endif
